"""Añadir reviewed_at a control

Revision ID: 9330b2de4dcf
Revises: b7d4f6b91551
Create Date: 2025-11-06 15:03:02.195522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9330b2de4dcf'
down_revision = 'b7d4f6b91551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controls', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controls', 'reviewed_at')
    # ### end Alembic commands ###