"""Revisión del modelo de riesgo y adición del modelo de área

Revision ID: b7d4f6b91551
Revises: b8a1c12b2873
Create Date: 2025-11-06 12:52:26.817498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d4f6b91551'
down_revision = 'b8a1c12b2873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.create_index(op.f('ix_areas_name'), 'areas', ['name'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.add_column('risks', sa.Column('area_id', sa.Integer(), nullable=False))
    op.add_column('risks', sa.Column('process_name', sa.String(length=255), nullable=False))
    op.add_column('risks', sa.Column('risk_description', sa.Text(), nullable=False))
    op.add_column('risks', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('_organization_risk_code_uc', 'risks', type_='unique')
    op.create_foreign_key(None, 'risks', 'areas', ['area_id'], ['id'])
    op.drop_column('risks', 'risk_code')
    op.drop_column('risks', 'description')
    op.drop_column('risks', 'cause')
    op.drop_column('risks', 'status')
    op.drop_column('risks', 'process')
    op.drop_column('risks', 'process_stage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risks', sa.Column('process_stage', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('risks', sa.Column('process', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('risks', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('risks', sa.Column('cause', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('risks', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('risks', sa.Column('risk_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'risks', type_='foreignkey')
    op.create_unique_constraint('_organization_risk_code_uc', 'risks', ['organization_id', 'risk_code'])
    op.drop_column('risks', 'reviewed_at')
    op.drop_column('risks', 'risk_description')
    op.drop_column('risks', 'process_name')
    op.drop_column('risks', 'area_id')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_areas_name'), table_name='areas')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_table('areas')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###