"""Add full_name column to User model

Revision ID: b8a1c12b2873
Revises: 59eeb8bed4c9
Create Date: 2025-10-24 02:23:52.401317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8a1c12b2873'
down_revision = '59eeb8bed4c9'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Paso 1: Llenar los valores NULL en full_name antes de aplicar NOT NULL
    op.execute("UPDATE users SET full_name = email WHERE full_name IS NULL")
    
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint('_organization_email_uc', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint('users_organization_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_organization_id_fkey', 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('_organization_email_uc', 'users', ['organization_id', 'email'])
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###