"""add_assigned_to_field

Revision ID: e4d8f9c12a3b
Revises: 6a74d8c18b08
Create Date: 2025-11-21 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d8f9c12a3b'
down_revision = '6a74d8c18b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controls', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'controls', 'users', ['assigned_to_id'], ['id'])
    op.add_column('risks', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'risks', 'users', ['assigned_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'risks', type_='foreignkey')
    op.drop_column('risks', 'assigned_to_id')
    op.drop_constraint(None, 'controls', type_='foreignkey')
    op.drop_column('controls', 'assigned_to_id')
    # ### end Alembic commands ###

